### ISSUE TITLE
Disable binary metrics for continuous traits

### ISSUE THREAD

**Issue by nebfield** [intervene-EU-H2020/prs-method-compare#17]
e.g. Height + odds ratio -> weird empty plots

@remomomo I think only r2 and beta should be enabled for continuous traits, right?

**Comment by remomomo** [comment]
Yes 👍 On Oct 6, 2023, at 15:12, Benjamin Wingfield ***@***.***> wrote:﻿
e.g. Height + odds ratio -> weird empty plots
@remomomo I think only r2 and beta should be enabled for continuous traits, right?
